export const CONTRACT_ID = "CDUUXVRIOXIDO2P6IIEHVADUXTOKXP5NURU5FFSZKG5Z4FPJN2EGVOFO";
export const XLM_SAC_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const STROOPS_PER_XLM = 10_000_000;
